### ISSUE TITLE
Cannot add TPB to Jackett

### ISSUE THREAD

**Issue by my95z34** [zone117x/Jackett#20]
When adding, I now get a new error.

 Configuration failed: Could not find releases from this URL

I have libcurl in /usr/local/lib/libcurl.so.7, which I symlinked to /usr/lib/ in case that was the issue, and still no go.  Nothing shows up in the console so I have no logs to provide. =\

**Comment by sea3pea0** [comment]
I installed libcurl-dev. Now when adding tpb or morethan I get: Configuration Failed: libcurl.dll

**Comment by zone117x** [comment]
Should be fixed in latest release, curl was not getting referenced correctly

**Comment by my95z34** [comment]
I'm still getting the original error mentioned, with no other output from the terminal.  FYI, I'm running in a FreeNAS Jail.

**Comment by zone117x** [comment]
You have libcurl-dev installed?

**Comment by my95z34** [comment]
As far as I know.  I can curl, and I have libcurl in /usr/local/lib/libcurl.so.7, which I also symlinked to /usr/lib in case that was the issue.  But didn't help.

**Comment by JesCR** [comment]
Same error here, Works proper with demonid and speedcd, but don't accept tpb...

**Comment by cassioac** [comment]
Has jacket dropped TPB?
